version: '3'

services:
  user-database:
    container_name: 'user-database'
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=testuser
      - POSTGRES_DB=users
    ports:
      - "5432:5432"
  post-database:
    container_name: 'post-database'
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postuser
      - POSTGRES_DB=posts
    ports:
      - "5433:5432"
  user-service-app:
    container_name: 'user-service-app'
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - user-database
  post-service-app:
    container_name: 'post-service-app'
    build: ./post-service
    ports:
      - "8082:8082"
    depends_on:
      - post-database
